# Generated by Django 3.0.8 on 2020-07-27 05:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jamoat',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32642)),
                ('objectid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('region', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('district', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('id', models.CharField(blank=True, max_length=50, null=True)),
                ('cadastral_field', models.CharField(blank=True, db_column='cadastral_', max_length=50, null=True)),
                ('type', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('standard_n', models.CharField(blank=True, max_length=50, null=True)),
                ('alternativ', models.CharField(blank=True, max_length=50, null=True)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('district_e', models.CharField(blank=True, max_length=30, null=True)),
                ('jamoat_eng', models.CharField(blank=True, max_length=30, null=True)),
                ('jambi_name', models.CharField(blank=True, max_length=22, null=True)),
                ('altern_eng', models.CharField(blank=True, max_length=22, null=True)),
                ('name_rg', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'jamoat',
                'managed': False,
            },
        ),
    ]
